version: 0.0
os: linux
files:
   - source: /
     destination: /usr/share/nginx/html/
hooks:
  BeforeInstall:
    - location: scripts/clearFile.sh
      runas: root
   AfterInstall:
    - location: scripts/restartnginx.sh
      runas: root